# Generated by Django 5.1.2 on 2024-10-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TerminosYCondiciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acepto_terminos', models.BooleanField(default=False)),
                ('fecha_aceptacion', models.DateTimeField(auto_now_add=True)),
                ('id_usuario', models.IntegerField()),
            ],
            options={
                'db_table': 'terminos_condiciones',
            },
        ),
    ]
