# Generated by Django 5.1.2 on 2024-10-26 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminosycondiciones',
            name='id_usuario',
            field=models.CharField(max_length=255),
        ),
    ]
