# Generated by Django 5.1.2 on 2024-11-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_productos_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.IntegerField(verbose_name='Precio del producto'),
        ),
    ]
