# Generated by Django 5.1.2 on 2024-11-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_productos_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Imagen del producto'),
        ),
    ]
