# Generated by Django 5.1.2 on 2024-11-19 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_productos_destacado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos', verbose_name='Imagen del producto'),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255, unique=True, verbose_name='Código de la venta')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de la venta')),
                ('nombre_cliente', models.CharField(max_length=255, verbose_name='Nombre del cliente')),
                ('apellido_cliente', models.CharField(max_length=255, verbose_name='Apellido del cliente')),
                ('rut_cliente', models.CharField(max_length=25, verbose_name='RUT del cliente')),
                ('email_cliente', models.EmailField(max_length=255, verbose_name='Email del cliente')),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Descuento aplicado')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor total de la venta')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario asociado')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'ventas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='TransaccionWebpay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, verbose_name='Token de la transacción')),
                ('fecha_transaccion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de la transacción')),
                ('estado', models.CharField(choices=[('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='aprobada', max_length=50, verbose_name='Estado de la transacción')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto de la transacción')),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.venta', verbose_name='Venta asociada')),
            ],
            options={
                'verbose_name': 'Transacción Webpay',
                'verbose_name_plural': 'Transacciones Webpay',
                'db_table': 'transacciones_webpay',
            },
        ),
        migrations.CreateModel(
            name='ProductoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.productos', verbose_name='Producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.venta', verbose_name='Código de venta')),
            ],
            options={
                'verbose_name': 'Producto en Venta',
                'verbose_name_plural': 'Productos en Venta',
                'db_table': 'productos_venta',
            },
        ),
    ]
