# Generated by Django 5.1.2 on 2024-12-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_productos_imagen_venta_transaccionwebpay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=255),
        ),
    ]
