# Generated by Django 5.1.2 on 2024-12-01 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_userprofile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='perfil_usuario',
        ),
    ]
