# Generated by Django 5.1.2 on 2024-12-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_alter_userprofile_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('motivo', models.CharField(max_length=255)),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'soporte',
            },
        ),
    ]
