# Generated by Django 5.1.2 on 2024-12-07 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_soporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='soporte',
            name='codigo',
            field=models.CharField(default=0, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rut',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
