# Generated by Django 5.1.2 on 2024-12-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_venta_calle_venta_celular_venta_comuna_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoventa',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='transaccionwebpay',
            name='venta',
        ),
        migrations.AddField(
            model_name='venta',
            name='tokenWebpay',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='Descuento aplicado'),
        ),
    ]
