# Generated by Django 5.1.2 on 2024-12-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_venta_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='despachador',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Despachador'),
        ),
        migrations.AddField(
            model_name='venta',
            name='numero_envio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número de Envío'),
        ),
    ]
